# Site settings
title: Christoph Wurst 
description: My personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.wuc.me" # the base hostname & protocol for your site
github_username: ChristophWurst
flickr_username: doubletight

# Build settings
markdown: kramdown
