# Site settings
title: Christoph Wurst 
description: My personal blog on technology and other things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ChristophWurst.github.io" # the base hostname & protocol for your site
github_username: ChristophWurst
flickr_username: doubletight

# Build settings
markdown: kramdown
